### ISSUE TITLE
How to add font to editor?

### ISSUE THREAD

**Issue by DenniLa2** [KillerCodeMonkey/ng-quill#137]
My css looks like this:
```css 
   .ff-alegreya-sans {  
      font-family: 'Alegreya Sans', sans-serif;  
    }  
    @font-face {  
      font-family: 'Alegreya Sans';  
    }
```

and config looks like:
```javascript
app.config(['ngQuillConfigProvider', function (ngQuillConfigProvider) {
  const config = {
    modules: {
      toolbar: [
        [{ 'font': ['Alegreya Sans'] }],
      ]
    }
  };

  ngQuillConfigProvider.set(config)
}]);
```

In ng-quill-toolbar in font-list i see only 'Sans Serif'. How to add  'Alegreya Sans' and remove 'Sans Serif'?
